ls:
  .js: kebab-case
  .jsx: kebab-case
  .ts: kebab-case
  .tsx: kebab-case
  .config.js: kebab-case
  .d.ts: kebab-case
  .json: kebab-case
  .md: kebab-case
ignore:
  - node_modules
  - ./packages/website/.next
  - ./packages/website/src/pages
  - ./packages/website/node_modules
  - ./packages/website/.serverless
  - ./packages/website/.serverless_nextjs
  - ./packages/sanity/node_modules
  - ./packages/sanity/dist
  - ./packages/sanity/sanity.config.ts
  - ./packages/sanity/sanity.cli.ts
  - ./packages/sanity/.eslintrc.js
